name: CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  

      - name: Install Dependencies
        run: |
          
          echo "No dependencies to install."

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      
      - name: Run Vale Tests
        run: |
          chmod +x scripts/run-vale-no-sync.sh  
          chmod +x scripts/run-vale.sh
          scripts/run-vale.sh sync
          python3 tests/test_vale_rules.py  
